export const createUserConstants = {
    DATA_REQUEST: 'MANAGER_DATA_REQUEST',
    DATA_SUCCESS: 'MANAGER_DATA_SUCCESS',
    DATA_FAILURE: 'MANAGER_DATA_FAILURE',

    LOGOUT: 'MANAGER_LOGOUT',

    CREATE_USER_REQUEST: 'MANAGER_CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'MANAGER_CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'MANAGER_CREATE_USER_FAILURE'


};
