export const specialUserConstants = {
    DATA_REQUEST: 'SUPER_USER_DATA_REQUEST',
    DATA_SUCCESS: 'SUPER_USER_DATA_SUCCESS',
    DATA_FAILURE: 'SUPER_USER_DATA_FAILURE',

    LOGOUT: 'SUPER_USER_LOGOUT',

    CREATE_USER_REQUEST: 'SUPER_USER_CREATE_USER_REQUEST',
    CREATE_USER_SUCCESS: 'SUPER_USER_CREATE_USER_SUCCESS',
    CREATE_USER_FAILURE: 'SUPER_USER_CREATE_USER_FAILURE'


};
