export const userConstants= {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGOUT: "LOGOUT",

    GET_USER_REQUEST: "GETTING_USER_REQUEST",
    GET_USER_SUCCESS: "GETTING_USER_SUCCESS",
    GET_USER_FAILURE: "GETTING_USER_FAILURE",
    // GET_USER: "GETTING_USER",

};